// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx_ODAZukr2hAA0irUVUPtfvTf_7P7bBo',
    appId: '1:1044479013616:web:23d96ef73ef8a5ef7b8835',
    messagingSenderId: '1044479013616',
    projectId: 'malaysia-travel-351de',
    authDomain: 'malaysia-travel-351de.firebaseapp.com',
    storageBucket: 'malaysia-travel-351de.firebasestorage.app',
    measurementId: 'G-JBGBSFWLCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEmvbyfyZnujPyZ1Em-womG21waaK7ww0',
    appId: '1:1044479013616:android:9a89cd75118060437b8835',
    messagingSenderId: '1044479013616',
    projectId: 'malaysia-travel-351de',
    storageBucket: 'malaysia-travel-351de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7q5U7NJJbf7ZUetUAPRVqmtCOKKMEeww',
    appId: '1:1044479013616:ios:36c83fad0a4c4ae97b8835',
    messagingSenderId: '1044479013616',
    projectId: 'malaysia-travel-351de',
    storageBucket: 'malaysia-travel-351de.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7q5U7NJJbf7ZUetUAPRVqmtCOKKMEeww',
    appId: '1:1044479013616:ios:36c83fad0a4c4ae97b8835',
    messagingSenderId: '1044479013616',
    projectId: 'malaysia-travel-351de',
    storageBucket: 'malaysia-travel-351de.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx_ODAZukr2hAA0irUVUPtfvTf_7P7bBo',
    appId: '1:1044479013616:web:e0f274386204860a7b8835',
    messagingSenderId: '1044479013616',
    projectId: 'malaysia-travel-351de',
    authDomain: 'malaysia-travel-351de.firebaseapp.com',
    storageBucket: 'malaysia-travel-351de.firebasestorage.app',
    measurementId: 'G-1B97G59SNV',
  );
}
