import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform;

/// Generated by FlutterFire CLI in real setup.
/// This placeholder keeps compilation valid and forces explicit setup.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'Firebase options are missing for $defaultTargetPlatform.\n'
      'Run these commands in the project root:\n'
      'dart pub global activate flutterfire_cli\n'
      'flutterfire configure',
    );
  }

  static bool get isConfigured {
    // Placeholder always means not configured.
    return false;
  }
}
